export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  STRUCTURE_ADMIN = 'STRUCTURE_ADMIN',
  STRUCTURE_CAISSE = 'STRUCTURE_CAISSE',
  SERVEUR = 'SERVEUR',
  AGENCE_ADMIN = 'AGENCE_ADMIN',
  AGENCE_CAISSE = 'AGENCE_CAISSE',
  MAGASIN_ADMIN = 'MAGASIN_ADMIN',
  MAGASIN_CAISSE = 'MAGASIN_CAISSE',
}
